language:
   - python

services:
   - elasticsearch

python:
   - "2.5"
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "pypy"

install:
   - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install chardet2; fi 
   - pip install requests simplejson argparse
   - python setup.py install

script:
   - python test_esclient.py
